/* Generated by tools/v1-proof/review.py; edit model.json. */
window.HuxProof = {
  "model": {
    "name": "V1-PROOF",
    "revision": "2026-09-28-A",
    "status": "active planning model; hardware unvalidated",
    "actuators": {
      "wheels": 2,
      "legs": 2
    },
    "limits": {
      "budget_usd_exclusive": 1000,
      "mass_target_kg": 2.5,
      "mass_max_kg": 3.0,
      "speed_ms": 0.5,
      "cruise_ms": 0.25
    },
    "geometry": {
      "wheel_diameter_mm": 100,
      "wheel_width_mm": 25,
      "wheel_track_mm": 230,
      "link_length_mm": 110,
      "pivot_separation_mm": 40,
      "leg_angle_deg": [
        15,
        45
      ],
      "neutral_angle_deg": 30,
      "body_above_lower_pivot_mm": 150,
      "body_width_mm": 110,
      "body_depth_mm": 120,
      "leg_reduction": 3,
      "transmission_efficiency_assumed": 0.85
    },
    "power": {
      "battery_class": "3S lithium pack, approximately 2.2 Ah",
      "nominal_v": 11.1,
      "full_v": 12.6,
      "screen_min_v": 9.9,
      "capacity_ah": 2.2
    },
    "wheel_screen": {
      "reference": "Pololu 4752, 30:1 37D 12 V gearmotor with encoder",
      "reference_v": 12,
      "no_load_rpm": 330,
      "stall_extrapolation_nm": 1.372931,
      "stall_extrapolation_a": 5.5,
      "no_load_a": 0.2,
      "proposed_peak_current_limit_a": 2.5,
      "proposed_rms_current_limit_a": 1.2,
      "lean_screen_deg": 10,
      "rolling_resistance_assumed": 0.03,
      "demand_multiplier": 2.5,
      "minimum_measured_peak_nm": 0.5,
      "minimum_measured_continuous_nm": 0.15
    },
    "leg_screen": {
      "worst_two_wheel_load_share": 0.6,
      "required_mounted_hold_nm": 0.75,
      "required_short_peak_nm": 1.0,
      "hold_test_minutes": 10
    },
    "mass_items": [
      {
        "item": "Two wheel gearmotors with encoders",
        "kg": 0.4
      },
      {
        "item": "Wheels, hubs and axle support bearings",
        "kg": 0.25
      },
      {
        "item": "Two leg servos",
        "kg": 0.14
      },
      {
        "item": "Links, pivots, belts and pulleys",
        "kg": 0.32
      },
      {
        "item": "Chassis and fasteners",
        "kg": 0.38
      },
      {
        "item": "Battery",
        "kg": 0.2
      },
      {
        "item": "MCU, IMU, receiver and drivers",
        "kg": 0.15
      },
      {
        "item": "Wiring, regulators and switches",
        "kg": 0.15
      },
      {
        "item": "Rest skids and bumpers",
        "kg": 0.12
      },
      {
        "item": "Unallocated mass allowance",
        "kg": 0.39
      }
    ],
    "budget": {
      "shipping_tax_usd": 100,
      "repair_contingency_usd": 125,
      "confirmed_reuse_credit_usd": 0,
      "rows": [
        {
          "id": "wheel_motors",
          "qty": 2,
          "item": "Encoder gearmotors, 12 V / 30:1 class",
          "unit_cap_usd": 62.5,
          "stage": "P1",
          "reuse": "Only a matched pair with useful encoders, reversal response and load data",
          "source": "wheel_motor"
        },
        {
          "id": "wheel_drivers",
          "qty": 2,
          "item": "Bidirectional H-bridges, current sensing and adjustable limiting",
          "unit_cap_usd": 50,
          "stage": "P1",
          "reuse": "Existing drone ESCs do not substitute for a brushed H-bridge",
          "source": "wheel_driver"
        },
        {
          "id": "leg_servos",
          "qty": 2,
          "item": "Small position servos, ST3215 12 V class",
          "unit_cap_usd": 30,
          "stage": "P3",
          "reuse": "Existing servos only after mounted hold and feedback tests",
          "source": "leg_servo"
        },
        {
          "id": "leg_hardware",
          "qty": 1,
          "item": "Two 3:1 reductions, shafts, pivots, bearings, stops and lock pins",
          "unit_cap_usd": 60,
          "stage": "P3",
          "reuse": "Shop bearings, belts and hardware after dimensions are measured"
        },
        {
          "id": "wheels",
          "qty": 1,
          "item": "Two rubber wheels, hubs and supported axle hardware",
          "unit_cap_usd": 35,
          "stage": "P1",
          "reuse": "Approximately 90\u2013110 mm wheels; update model for actual diameter"
        },
        {
          "id": "controller",
          "qty": 1,
          "item": "MCU, IMU and servo interface allowance",
          "unit_cap_usd": 40,
          "stage": "P0",
          "reuse": "F765/F722/Mamba or ESP32 plus IMU, subject to pin/timing check"
        },
        {
          "id": "manual_link",
          "qty": 1,
          "item": "Manual input/link replacement allowance",
          "unit_cap_usd": 60,
          "stage": "P0",
          "reuse": "TBS Nano plus compatible transmitter, or existing laptop/gamepad link"
        },
        {
          "id": "battery",
          "qty": 1,
          "item": "Compatible 3S battery",
          "unit_cap_usd": 35,
          "stage": "P1",
          "reuse": "Healthy pack with known cell count, condition and connectors"
        },
        {
          "id": "charger",
          "qty": 1,
          "item": "Compatible balance charger, supply and lead",
          "unit_cap_usd": 45,
          "stage": "P1",
          "reuse": "Existing compatible charger and power supply"
        },
        {
          "id": "power",
          "qty": 1,
          "item": "Logic/servo regulation, fuse, kill, transient protection",
          "unit_cap_usd": 45,
          "stage": "P1",
          "reuse": "Only parts meeting rail voltage and current requirements"
        },
        {
          "id": "harness",
          "qty": 1,
          "item": "Wire, connectors, encoder level shifting and strain relief",
          "unit_cap_usd": 30,
          "stage": "P1",
          "reuse": "Existing wire/connectors of appropriate size"
        },
        {
          "id": "structure",
          "qty": 1,
          "item": "Scrap/COTS frame, links, brackets, fasteners and prototype material",
          "unit_cap_usd": 60,
          "stage": "P1",
          "reuse": "Aluminum, plywood or suitable existing stock; no carbon requirement"
        },
        {
          "id": "fixture",
          "qty": 1,
          "item": "Catch frame, rest skids and padding materials",
          "unit_cap_usd": 20,
          "stage": "P1",
          "reuse": "Shop scrap and straps; fixtures remain outside robot mass"
        }
      ]
    },
    "sources": [
      {
        "id": "wheel_motor",
        "title": "Pololu 4752 gearmotor",
        "url": "https://www.pololu.com/product/4752",
        "checked": "2026-09-28",
        "listed_usd": 60.95,
        "note": "Reference, not selected inventory. Stall torque/current are extrapolated, not continuous ratings."
      },
      {
        "id": "wheel_driver",
        "title": "Pololu G2 18v17 H-bridge",
        "url": "https://www.pololu.com/product/2991",
        "checked": "2026-09-28",
        "listed_usd": 44.95,
        "note": "Reference. Factory current limit is much too high; verify a lowered limit before motor operation."
      },
      {
        "id": "leg_servo",
        "title": "Waveshare ST3215 series",
        "url": "https://www.waveshare.com/product/st3215-servo.htm",
        "checked": "2026-09-28",
        "listed_range_usd": [
          16.99,
          21.99
        ],
        "note": "Select the 12 V variant when checking fit. 30 kg-cm is not a demonstrated continuous holding rating."
      },
      {
        "id": "leg_servo_docs",
        "title": "Waveshare ST3215 documentation",
        "url": "https://www.waveshare.com/wiki/ST3215_Servo",
        "checked": "2026-09-28",
        "note": "Current page specifies 6\u201312.6 V for the 12 V version. Confirm actual revision and protect against regenerative voltage rise."
      }
    ]
  },
  "results": {
    "name": "V1-PROOF",
    "revision": "2026-09-28-A",
    "actuator_count": 4,
    "parts_cap_usd": 715.0,
    "total_cap_usd": 940.0,
    "headroom_usd": 60.0,
    "under_budget": true,
    "mass_allocation_kg": 2.5,
    "within_mass_limit": true,
    "overall_width_mm": 255,
    "poses": [
      {
        "angle_deg": 15,
        "axle_rearward_mm": 28.470094961277283,
        "pivot_above_axle_mm": 106.25184089179751,
        "overall_height_mm": 306.25184089179754,
        "servo_from_neutral_deg": -45
      },
      {
        "angle_deg": 45,
        "axle_rearward_mm": 77.78174593052022,
        "pivot_above_axle_mm": 77.78174593052023,
        "overall_height_mm": 277.78174593052023,
        "servo_from_neutral_deg": 45
      }
    ],
    "height_travel_mm": 28.47009496127731,
    "axle_fore_aft_travel_mm": 49.31165096924293,
    "worst_static_servo_nm": 0.5386157135847552,
    "wheel_at_target_mass": {
      "rpm": 95.4929658551372,
      "screen_voltage_v": 9.9,
      "no_load_rpm": 272.25,
      "demand_nm_per_wheel": 0.316260575117194,
      "available_peak_nm_estimate": 0.5958002452830188,
      "current_limited_nm_estimate": 0.5958002452830188,
      "passes_preliminary_screen": true,
      "hardware_validated": false
    },
    "wheel_at_max_mass": {
      "rpm": 95.4929658551372,
      "screen_voltage_v": 9.9,
      "no_load_rpm": 272.25,
      "demand_nm_per_wheel": 0.3795126901406329,
      "available_peak_nm_estimate": 0.5958002452830188,
      "current_limited_nm_estimate": 0.5958002452830188,
      "passes_preliminary_screen": true,
      "hardware_validated": false
    },
    "hardware_validated": false,
    "fabrication_ready": false
  }
};
